Controllers/CountryController.cs
using System;
using VPPModel;
using System.Web.Mvc;
using Newtonsoft.Json;
using Country_BL;
using System.IO;
using ErrorLog_BL;
using Message_BL;

namespace VPPWeb.Controllers
{
    public class CountryController : Controller
    {
        // GET: Country
        public ActionResult BannerPhotoListing()
        {
            return View();
        }

        [HttpPost]
        public string CountryPhoto_Update()
        {
            string j1 = HttpContext.Request.Params.Get("CountryModel");
            CountryModel countryModel = JsonConvert.DeserializeObject<CountryModel>(j1);
            try
            {
                CountryBL countryBL = new CountryBL();

                for (int i = 0; i < Request.Files.Count; i++)
                {
                    string key = Request.Files.GetKey(i);
                    if (key == "banner1")
                    {
                        if (!string.IsNullOrWhiteSpace(countryModel.Bannerphoto1))
                        {
                            if (System.IO.File.Exists(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + countryModel.Bannerphoto1)))
                                System.IO.File.Delete(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + countryModel.Bannerphoto1));
                        }

                        countryModel.Bannerphoto1 = "BannerPhotos/" + countryModel.CountryID + "_banner1_"  + DateTime.Now.ToString("yyyyMMddhhmmss") + ".jpg";
                        Request.Files[i].SaveAs(Path.Combine(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/"), countryModel.Bannerphoto1));
                    }
                    else if (key == "banner2")
                    {
                        if (!string.IsNullOrWhiteSpace(countryModel.Bannerphoto2))
                        {
                            if (System.IO.File.Exists(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + countryModel.Bannerphoto2)))
                                System.IO.File.Delete(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + countryModel.Bannerphoto2));
                        }

                        countryModel.Bannerphoto2 = "BannerPhotos/" + countryModel.CountryID + "_banner2_" + DateTime.Now.ToString("yyyyMMddhhmmss") + ".jpg";
                       
                        Request.Files[i].SaveAs(Path.Combine(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/"), countryModel.Bannerphoto2));
                    }
                    else if (key == "banner3")
                    {
                        if (!string.IsNullOrWhiteSpace(countryModel.Bannerphoto3))
                        {
                            if (System.IO.File.Exists(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + countryModel.Bannerphoto3)))
                                System.IO.File.Delete(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + countryModel.Bannerphoto3));
                        }

                        countryModel.Bannerphoto3 = "BannerPhotos/" + countryModel.CountryID + "_banner3_" + DateTime.Now.ToString("yyyyMMddhhmmss") + ".jpg";

                        Request.Files[i].SaveAs(Path.Combine(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/"), countryModel.Bannerphoto3));
                    }
                    else if (key == "banner4")
                    {
                        if (!string.IsNullOrWhiteSpace(countryModel.Bannerphoto4))
                        {
                            if (System.IO.File.Exists(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + countryModel.Bannerphoto4)))
                                System.IO.File.Delete(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + countryModel.Bannerphoto4));
                        }

                        countryModel.Bannerphoto4 = "BannerPhotos/" + countryModel.CountryID + "_banner4_" + DateTime.Now.ToString("yyyyMMddhhmmss") + ".jpg";
                        Request.Files[i].SaveAs(Path.Combine(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/"), countryModel.Bannerphoto4));
                    }
                    else if (key == "banner5")
                    {
                        if (!string.IsNullOrWhiteSpace(countryModel.Bannerphoto5))
                        {
                            if (System.IO.File.Exists(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + countryModel.Bannerphoto5)))
                                System.IO.File.Delete(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + countryModel.Bannerphoto5));
                        }

                        countryModel.Bannerphoto5 = "BannerPhotos/" + countryModel.CountryID + "_banner5_" + DateTime.Now.ToString("yyyyMMddhhmmss") + ".jpg";

                        Request.Files[i].SaveAs(Path.Combine(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/"), countryModel.Bannerphoto5));
                    }
                    else if (key == "banner6")
                    {
                        if (!string.IsNullOrWhiteSpace(countryModel.Bannerphoto6))
                        {
                            if (System.IO.File.Exists(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + countryModel.Bannerphoto6)))
                                System.IO.File.Delete(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + countryModel.Bannerphoto6));

                        }
                        countryModel.Bannerphoto6 = "BannerPhotos/" + countryModel.CountryID + "_banner6_" + DateTime.Now.ToString("yyyyMMddhhmmss") + ".jpg";
                        
                        Request.Files[i].SaveAs(Path.Combine(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/"), countryModel.Bannerphoto6));
                    }
                    else if (key == "footer1")
                    {
                        if (!string.IsNullOrWhiteSpace(countryModel.Footerphoto1))
                        {
                            if (System.IO.File.Exists(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + countryModel.Footerphoto1)))
                                System.IO.File.Delete(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + countryModel.Footerphoto1));
                        }

                        countryModel.Footerphoto1 = "BannerPhotos/" + countryModel.CountryID + "_footer1_" + DateTime.Now.ToString("yyyyMMddhhmmss") + ".jpg";
                        Request.Files[i].SaveAs(Path.Combine(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/"), countryModel.Footerphoto1));
                    }
                }

                return countryBL.CountryPhoto_Update(countryModel);
            }
            catch (Exception exception)
            {
                ErrorLogModel errorLogModel = new ErrorLogModel
                {
                    ErrorMessage = exception.Message,
                    UpdatedBy = countryModel.UpdatedBy
                };

                ErrorLogBL errorLogBL = new ErrorLogBL();
                errorLogBL.ErrorLog_Insert(errorLogModel);

                MessageBL messageBL = new MessageBL();
                MessageModel messageModel = new MessageModel
                {
                    MessageID = "E007"
                };
                return messageBL.Message_Select(messageModel);
            }
        }

        public ActionResult CountryPageFooter()
        {
            return View();
        }

        public ActionResult BannerListing()
        {
            return View();
        }
    }
}

Views/Country/BannerListing.cshtml
@{
    ViewBag.Title = "BannerListing";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>BannerListing</h2>

Views/Country/BannerPhotoListing.cshtml
@{
    ViewBag.Title = "BannerPhotoListing";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-wrapper">
    <!-- Page body start -->
    <div class="page-body">
        <div class="row">
            <div class="col-sm-12">
                <!-- Basic Form Inputs card start -->
                <div class="card">
                    <div class="card-header">
                        <h5>Banner Photos</h5>
                    </div>
                    <div class="card-block">
                        <div class="form-group row">
                            <div class="col-sm-12 col-lg-1 col-md-1">
                                <label col-form-label">Country:</label>
                            </div>
                            <div class="col-sm-12 col-lg-2 col-md-2">
                                <select id="ddlCountry" onchange="CountryChange()" class="form-control">
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 col-lg-1 col-md-1">
                                <label col-form-label">Banner1:</label>
                            </div>
                            <div class="col-sm-12 col-lg-10 col-md-10">
                                <div id="divBanner1" style="height: 200px;background-image: url( @Url.Content("~/SystemImages/noimage.jpg")) ;background-size: 100% 100%;"></div>
                            </div>
                        </div>
                        <div class="form-group row" style="border-bottom:dashed 1px black">
                            <div class="col-sm-12 col-lg-1 col-md-1">
                                <label col-form-label">Banner Link1:</label>
                            </div>
                            <div class="col-sm-12 col-lg-9 col-md-9">
                                <input id="BannerUrl1" type="text" class="form-control" />
                            </div>
                            <div class="col-sm-12 col-lg-2 col-md-2">
                                <button class="btn btn-danger" onclick="RemoveBanner(1);" style="padding: .5rem .75rem">Remove Banner1</button>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 col-lg-1 col-md-1">
                                <label col-form-label">Banner2:</label>
                            </div>
                            <div class="col-sm-12 col-lg-10 col-md-10">
                                <div id="divBanner2" style="height: 200px;background-image: url( @Url.Content("~/SystemImages/noimage.jpg")) ;background-size: 100% 100%;"></div>
                            </div>
                        </div>
                        <div class="form-group row" style="border-bottom:dashed 1px black">
                            <div class="col-sm-12 col-lg-1 col-md-1">
                                <label col-form-label">Banner Link2:</label>
                            </div>
                            <div class="col-sm-12 col-lg-9 col-md-9">
                                <input id="BannerUrl2" type="text" class="form-control" />
                            </div>
                            <div class="col-sm-12 col-lg-2 col-md-2">
                                <button class="btn btn-danger" onclick="RemoveBanner(2);" style="padding: .5rem .75rem">Remove Banner2</button>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 col-lg-1 col-md-1">
                                <label col-form-label">Banner3:</label>
                            </div>
                            <div class="col-sm-12 col-lg-10 col-md-10">
                                <div id="divBanner3" style="height: 200px;background-image: url( @Url.Content("~/SystemImages/noimage.jpg")) ;background-size: 100% 100%;"></div>
                            </div>
                        </div>
                        <div class="form-group row" style="border-bottom:dashed 1px black">
                            <div class="col-sm-12 col-lg-1 col-md-1">
                                <label col-form-label">Banner Link3:</label>
                            </div>
                            <div class="col-sm-12 col-lg-9 col-md-9">
                                <input id="BannerUrl3" type="text" class="form-control" />
                            </div>
                            <div class="col-sm-12 col-lg-2 col-md-2">
                                <button class="btn btn-danger" onclick="RemoveBanner(3);" style="padding: .5rem .75rem">Remove Banner3</button>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 col-lg-1 col-md-1">
                                <label col-form-label">Banner4:</label>
                            </div>
                            <div class="col-sm-12 col-lg-10 col-md-10">
                                <div id="divBanner4" style="height: 200px;background-image: url( @Url.Content("~/SystemImages/noimage.jpg")) ;background-size: 100% 100%;"></div>
                            </div>
                        </div>
                        <div class="form-group row" style="border-bottom:dashed 1px black">
                            <div class="col-sm-12 col-lg-1 col-md-1">
                                <label col-form-label">Banner Link4:</label>
                            </div>
                            <div class="col-sm-12 col-lg-9 col-md-9">
                                <input id="BannerUrl4" type="text" class="form-control" />
                            </div>
                            <div class="col-sm-12 col-lg-2 col-md-2">
                                <button class="btn btn-danger" onclick="RemoveBanner(4);" style="padding: .5rem .75rem">Remove Banner4</button>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 col-lg-1 col-md-1">
                                <label col-form-label">Banner5:</label>
                            </div>
                            <div class="col-sm-12 col-lg-10 col-md-10">
                                <div id="divBanner5" style="height: 200px;background-image: url( @Url.Content("~/SystemImages/noimage.jpg")) ;background-size: 100% 100%;"></div>
                            </div>
                        </div>
                        <div class="form-group row" style="border-bottom:dashed 1px black">
                            <div class="col-sm-12 col-lg-1 col-md-1">
                                <label col-form-label">Banner Link5:</label>
                            </div>
                            <div class="col-sm-12 col-lg-9 col-md-9">
                                <input id="BannerUrl5" type="text" class="form-control" />
                            </div>
                            <div class="col-sm-12 col-lg-2 col-md-2">
                                <button class="btn btn-danger" onclick="RemoveBanner(5);" style="padding: .5rem .75rem">Remove Banner5</button>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 col-lg-1 col-md-1">
                                <label col-form-label">Banner6:</label>
                            </div>
                            <div class="col-sm-12 col-lg-10 col-md-10">
                                <div id="divBanner6" style="height: 200px;background-image: url( @Url.Content("~/SystemImages/noimage.jpg")) ;background-size: 100% 100%;"></div>
                            </div>
                        </div>
                        <div class="form-group row" style="border-bottom:dashed 1px black">
                            <div class="col-sm-12 col-lg-1 col-md-1">
                                <label col-form-label">Banner Link6:</label>
                            </div>
                            <div class="col-sm-12 col-lg-9 col-md-9">
                                <input id="BannerUrl6" type="text" class="form-control" />
                            </div>
                            <div class="col-sm-12 col-lg-2 col-md-2">
                                <button class="btn btn-danger" onclick="RemoveBanner(6);" style="padding: .5rem .75rem">Remove Banner6</button>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 col-lg-1 col-md-1">
                                <label col-form-label">Footer:</label>
                            </div>
                            <div class="col-sm-12 col-lg-10 col-md-10">
                                <div id="divFooter1" style="height: 100px;background-image: url( @Url.Content("~/SystemImages/noimage.jpg")) ;background-size: 100% 100%;"></div>
                            </div>
                        </div>
                        <div class="form-group row" style="border-bottom:dashed 1px black;padding-bottom:10px">
                            <div class="col-sm-12 col-lg-1 col-md-1">
                            </div>
                            <div class="col-sm-12 col-lg-9 col-md-9">

                            </div>
                            <div class="col-sm-12 col-lg-2 col-md-2">
                                <button class="btn btn-danger" onclick="RemoveFooter();" style="padding: .5rem .75rem">Remove Footer &nbsp;</button>
                            </div>
                        </div>
                        <div id="divSave" class="form-group row div-centerbtn">
                            <div class="col-sm-3">
                                <button type="button" id="btnSave" onclick="BannerPhotoSave();" class="btn btn-block btn-grd-info"><span id="btnSaveText">Save</span></button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Page body end -->
</div>
<input id="banner1upload" accept="image/*" class="hidden" type="file" onchange="changeBackground(this,'divBanner1');">
<input id="banner2upload" accept="image/*" class="hidden" type="file" onchange="changeBackground(this,'divBanner2');">
<input id="banner3upload" accept="image/*" class="hidden" type="file" onchange="changeBackground(this,'divBanner3');">
<input id="banner4upload" accept="image/*" class="hidden" type="file" onchange="changeBackground(this,'divBanner4');">
<input id="banner5upload" accept="image/*" class="hidden" type="file" onchange="changeBackground(this,'divBanner5');">
<input id="banner6upload" accept="image/*" class="hidden" type="file" onchange="changeBackground(this,'divBanner6');">
<input id="footer1upload" accept="image/*" class="hidden" type="file" onchange="changeBackground(this,'divFooter1');">

<input type="hidden" id="HBannerphoto1" />
<input type="hidden" id="HBannerphoto2" />
<input type="hidden" id="HBannerphoto3" />
<input type="hidden" id="HBannerphoto4" />
<input type="hidden" id="HBannerphoto5" />
<input type="hidden" id="HBannerphoto6" />
<input type="hidden" id="HFooterphoto1" />
<input id="HRemoveBannerNo" type="hidden" />
<input id="HRemoveBannerPhoto" type="hidden" />

<input id="HGetCountry" type="hidden" value="@Url.Action("GetCountry", "api/CountryApi")" />
<input id="HGetBannerPhoto" type="hidden" value="@Url.Action("GetCountryPhoto", "api/CountryApi")" />
<input id="HCountryPhotoUpdate" type="hidden" value="@Url.Action("CountryPhoto_Update", "Country")" />
<input id="HCountryPhotoUpdateapi" type="hidden" value="@Url.Action("CountryPhoto_Updateapi", "api/CountryApi")" />
<input id="HImageLocation" type="hidden" value="@Url.Content("~/SystemImages/")" />
<input id="HNoImageLocation" type="hidden" value="@Url.Content("~/SystemImages/noimage.jpg")" />

@section Scripts{
    <script src="@Url.Content("~/Scripts/country.js?v=7")"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            BannerPhotoLoad();
        });
    </script>
}

Views/Country/CountryPageFooter.cshtml
@{
    ViewBag.Title = "CountryPageFooter";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-wrapper">
    <!-- Page body start -->
    <div class="page-body">
        <div class="row">
            <div class="col-sm-12">
                <!-- Basic Form Inputs card start -->
                <div class="card">
                    <div class="card-header">
                        <h5>Page Footer Setting</h5>
                    </div>
                    <div class="card-block">
                        <div class="form-group row">
                            <div class="col-sm-12 col-lg-1 col-md-2">
                                <label col-form-label">Country:</label>
                            </div>
                            <div class="col-sm-12 col-lg-2 col-md-2">
                                <select id="ddlCountry" onchange="FooterCountryChange()" class="form-control form-control-sm">
                                </select>
                            </div>
                        </div>
                        <div style="display:none;" class="form-group row">
                            <div class="col-sm-12 col-lg-1 col-md-2">
                                <label col-form-label">Copyright Text:</label>
                            </div>
                            <div class="col-sm-12 col-lg-10 col-md-10">
                                <input type="text" id="txtCopyright" class="form-control form-control-sm" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 col-lg-1 col-md-2">
                                <label col-form-label">D-Link Web Page:</label>
                            </div>
                            <div class="col-sm-12 col-lg-11 col-md-10">
                                <div class="input-group nomarginbottom">
                                    <span class="input-group-addon customaddon" id="basic-addon2"><img src="@Url.Content("~/SystemImages/fav.ico")" /></span>
                                    <input type="text" id="txtDlinkUrl" class="form-control form-control-sm" />
                                </div>

                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 col-lg-1 col-md-2">
                                <label col-form-label">LinkedIn Url:</label>
                            </div>
                            <div class="col-sm-12 col-lg-11 col-md-10">
                                <div class="input-group nomarginbottom">
                                    <span class="input-group-addon customaddon" id="basic-addon2"><img src="@Url.Content("~/SystemImages/linkedin.ico")" /></span>
                                    <input type="text" id="txtLinkedIn" class="form-control form-control-sm" />
                                </div>

                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 col-lg-1 col-md-2">
                                <label col-form-label">Facebook Url:</label>
                            </div>
                            <div class="col-sm-12 col-lg-11 col-md-10">
                                <div class="input-group nomarginbottom">
                                    <span class="input-group-addon customaddon" id="basic-addon2"><img src="@Url.Content("~/SystemImages/facebook.ico")" /></span>
                                    <input type="text" id="txtFacebookUrl" class="form-control form-control-sm" />
                                </div>

                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 col-lg-1 col-md-2">
                                <label col-form-label">Twitter Url:</label>
                            </div>
                            <div class="col-sm-12 col-lg-11 col-md-10">
                                <div class="input-group nomarginbottom">
                                    <span class="input-group-addon customaddon" id="basic-addon2"><img src="@Url.Content("~/SystemImages/twitter.ico")" /></span>
                                    <input type="text" id="txtTwitterUrl" class="form-control form-control-sm" />
                                </div>

                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 col-lg-1 col-md-2">
                                <label col-form-label">Youtube Url:</label>
                            </div>
                            <div class="col-sm-12 col-lg-11 col-md-10">
                                <div class="input-group nomarginbottom">
                                    <span class="input-group-addon customaddon" id="basic-addon2"><img src="@Url.Content("~/SystemImages/youtube.ico")" /></span>
                                    <input type="text" id="txtYoutubeUrl" class="form-control form-control-sm" />
                                </div>

                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 col-lg-1 col-md-2">
                                <label col-form-label">Instagram Url:</label>
                            </div>
                            <div class="col-sm-12 col-lg-11 col-md-10">
                                <div class="input-group nomarginbottom">
                                    <span class="input-group-addon customaddon" id="basic-addon2"><img src="@Url.Content("~/SystemImages/instagram.ico")" /></span>
                                    <input type="text" id="txtInstagramUrl" class="form-control form-control-sm" />
                                </div>

                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 col-lg-1 col-md-2">
                                <label col-form-label">Shopee Url:</label>
                            </div>
                            <div class="col-sm-12 col-lg-11 col-md-10">
                                <div class="input-group nomarginbottom">
                                    <span class="input-group-addon customaddon" id="basic-addon2"><img src="@Url.Content("~/SystemImages/shopee.ico")" /></span>
                                    <input type="text" id="txtShopeeUrl" class="form-control form-control-sm" />
                                </div>

                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 col-lg-1 col-md-2">
                                <label col-form-label">Lazada Url:</label>
                            </div>
                            <div class="col-sm-12 col-lg-11 col-md-10">
                                <div class="input-group nomarginbottom">
                                    <span class="input-group-addon customaddon" id="basic-addon2"><img src="@Url.Content("~/SystemImages/lazada.ico")" /></span>
                                    <input type="text" id="txtLazadaUrl" class="form-control form-control-sm" />
                                </div>

                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 col-lg-1 col-md-2">
                                <label col-form-label">TikTok Url:</label>
                            </div>
                            <div class="col-sm-12 col-lg-11 col-md-10">
                                <div class="input-group nomarginbottom">
                                    <span class="input-group-addon customaddon" id="basic-addon2"><img src="@Url.Content("~/SystemImages/tiktok.ico")" /></span>
                                    <input type="text" id="txtTikTokUrl" class="form-control form-control-sm" />
                                </div>

                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 col-lg-1 col-md-2">
                                <label col-form-label">Contact Us:</label>
                            </div>
                            <div class="col-sm-12 col-lg-11 col-md-10">
                                <input type="text" id="txtContactUs" class="form-control form-control-sm" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 col-lg-1 col-md-2">
                                <label col-form-label">Privacy Policy:</label>
                            </div>
                            <div class="col-sm-12 col-lg-11 col-md-10">
                                <textarea id="txtPrivacyPolicy" class="form-control form-control-sm height300"></textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 col-lg-1 col-md-2">
                                <label col-form-label">Term & Conditions:</label>
                            </div>
                            <div class="col-sm-12 col-lg-11 col-md-10">
                                <textarea id="txtTermsNConditions" class="form-control form-control-sm height300"></textarea>
                            </div>
                        </div>
                        <div id="divSave" class="form-group row div-centerbtn">
                            <div class="col-sm-3">
                                <button type="button" id="btnSave" onclick="FooterPageFooterUpdate();" class="btn btn-block btn-grd-info"><span id="btnSaveText">Save</span></button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Page body end -->
</div>

<input id="HGetCountry" type="hidden" value="@Url.Action("GetCountry", "api/CountryApi")" />
<input id="HGetCountryFooter" type="hidden" value="@Url.Action("GetCountryPageFooter", "api/CountryApi")" />
<input id="HCountryFooterUpdate" type="hidden" value="@Url.Action("CountryPageFooterUpdate", "api/CountryApi")" />

@section Scripts{
    <script src="@Url.Content("~/Scripts/country.js?v=6")"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            FooterCountryLoad();
        });
    </script>
}