Controllers/RewardController.cs
using Newtonsoft.Json;
using System;
using System.Web.Mvc;
using VPPModel;
using Reward_BL;
using System.IO;
using ErrorLog_BL;
using Message_BL;
using System.Data;
using LumenWorks.Framework.IO.Csv;
using CKM_CommonFunction;

namespace VPPWeb.Controllers
{
    public class RewardController : Controller
    {
        public ActionResult RewardPrizeListing()
        {
            return View();
        }

        [HttpPost]
        public string RewardPrize_CUD()
        {
            string j1 = HttpContext.Request.Params.Get("RewardPrizeModel");
            RewardPrizeModel rewardPrizeModel = JsonConvert.DeserializeObject<RewardPrizeModel>(j1);
            try
            {
                RewardBL reward_BL = new RewardBL();

                if (!string.IsNullOrEmpty(rewardPrizeModel.RemoveProductPhoto))
                {
                    if (System.IO.File.Exists(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + rewardPrizeModel.RemoveProductPhoto)))
                        System.IO.File.Delete(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + rewardPrizeModel.RemoveProductPhoto));
                }

                if (!string.IsNullOrEmpty(rewardPrizeModel.RemoveQuotationPhoto))
                {
                    if (System.IO.File.Exists(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + rewardPrizeModel.RemoveQuotationPhoto)))
                        System.IO.File.Delete(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + rewardPrizeModel.RemoveQuotationPhoto));
                }

                for (int i = 0; i < Request.Files.Count; i++)
                {
                    string key = Request.Files.GetKey(i);
                    if (key == "product")
                    {

                        if (System.IO.File.Exists(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + rewardPrizeModel.ProductPhoto)))
                            System.IO.File.Delete(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + rewardPrizeModel.ProductPhoto));

                        rewardPrizeModel.ProductPhoto = "Product/" + rewardPrizeModel.ItemCode + DateTime.Now.ToString("yyyyMMddhhmmss") + ".jpg";

                        Request.Files[i].SaveAs(Path.Combine(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/"), rewardPrizeModel.ProductPhoto));
                    }
                    else if (key == "quotation")
                    {
                        if (System.IO.File.Exists(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + rewardPrizeModel.QuotationPhoto)))
                            System.IO.File.Delete(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + rewardPrizeModel.QuotationPhoto));

                        rewardPrizeModel.QuotationPhoto = "Quotation/" + rewardPrizeModel.ItemCode + DateTime.Now.ToString("yyyyMMddhhmmss") + ".jpg";

                        Request.Files[i].SaveAs(Path.Combine(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/"), rewardPrizeModel.QuotationPhoto));
                    }
                }

                return reward_BL.RewardPrize_CUD(rewardPrizeModel);
            }
            catch(Exception exception)
            {
                ErrorLogModel errorLogModel = new ErrorLogModel
                {
                    ErrorMessage = exception.Message,
                    UpdatedBy = rewardPrizeModel.UpdatedBy
                };

                ErrorLogBL errorLogBL = new ErrorLogBL();
                errorLogBL.ErrorLog_Insert(errorLogModel);

                MessageBL messageBL = new MessageBL();
                MessageModel messageModel = new MessageModel
                {
                    MessageID = "E007"
                };
                return messageBL.Message_Select(messageModel);
            }
        }

        [HttpPost]
        public string CheckRewardImport()
        {
            MessageBL messageBL = new MessageBL();
            string j1 = HttpContext.Request.Params.Get("RewardPrizeModel");
            RewardPrizeModel rewardPrizeModel = JsonConvert.DeserializeObject<RewardPrizeModel>(j1);

            if (Request.Files["rewardprizeupload"].FileName.EndsWith(".csv"))
            {
                Stream stream = Request.Files["rewardprizeupload"].InputStream;
                DataTable csvTable = new DataTable();
                using (CsvReader csvReader =
                    new CsvReader(new StreamReader(stream), true))
                {
                    csvTable.Load(csvReader);
                }

                if (!csvTable.Columns.Contains("Country") || !csvTable.Columns.Contains("Category") ||
                    !csvTable.Columns.Contains("ProductName") || !csvTable.Columns.Contains("RewardPointsRequired") ||
                    !csvTable.Columns.Contains("ValidTill") || !csvTable.Columns.Contains("PageType") ||
                    !csvTable.Columns.Contains("ExternalURL") || !csvTable.Columns.Contains("ProductDescriptions") ||
                    !csvTable.Columns.Contains("UnitCost") || !csvTable.Columns.Contains("Supplier"))
                {
                    MessageModel messageModel = new MessageModel
                    {
                        MessageID = "E015"
                    };
                    return messageBL.Message_Select(messageModel);
                }

                CommonFunction commonFunction = new CommonFunction();
                rewardPrizeModel.ImportJson = commonFunction.DataTableToJSONWithJSONNet(csvTable);

                RewardBL rewardBL = new RewardBL();

                return rewardBL.CheckRewardPrizeImport(rewardPrizeModel);
            }
            else
            {
                MessageModel messageModel = new MessageModel
                {
                    MessageID = "E014"
                };
                return messageBL.Message_Select(messageModel);
            }            
        }

        [HttpPost]
        public string RewardImportConfirm()
        {
            MessageBL messageBL = new MessageBL();
            string j1 = HttpContext.Request.Params.Get("RewardPrizeModel");
            RewardPrizeModel rewardPrizeModel = JsonConvert.DeserializeObject<RewardPrizeModel>(j1);

            try
            {
                if (Request.Files["rewardprizeupload"].FileName.EndsWith(".csv"))
                {
                    Stream stream = Request.Files["rewardprizeupload"].InputStream;
                    DataTable csvTable = new DataTable();
                    using (CsvReader csvReader =
                        new CsvReader(new StreamReader(stream), true))
                    {
                        csvTable.Load(csvReader);
                    }

                    CommonFunction commonFunction = new CommonFunction();
                    rewardPrizeModel.FileName = Request.Files["rewardprizeupload"].FileName;
                    rewardPrizeModel.ImportJson = commonFunction.DataTableToJSONWithJSONNet(csvTable);

                    RewardBL rewardBL = new RewardBL();
                    rewardBL.RewardPrize_ImportConfirm(rewardPrizeModel);

                    MessageModel messageModel = new MessageModel
                    {
                        MessageID = "I006"
                    };
                    return messageBL.Message_Select(messageModel);
                }
                else
                {
                    MessageModel messageModel = new MessageModel
                    {
                        MessageID = "E014"
                    };
                    return messageBL.Message_Select(messageModel);
                }
            }
            catch(Exception exception)
            {
                ErrorLogModel errorLogModel = new ErrorLogModel
                {
                    ErrorMessage = exception.Message,
                    UpdatedBy = rewardPrizeModel.UpdatedBy
                };

                ErrorLogBL errorLogBL = new ErrorLogBL();
                errorLogBL.ErrorLog_Insert(errorLogModel);

                MessageModel messageModel = new MessageModel
                {
                    MessageID = "E014"
                };
                return messageBL.Message_Select(messageModel);
            }

        }
    }
}

Views/Reward/RewardPrizeListing.cshtml
@{
    ViewBag.Title = "RewardPrizeListing";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="page-wrapper">
    <!-- Page body start -->
    <div class="page-body">
        <div class="row">
            <div class="col-sm-12">
                <!-- Basic Form Inputs card start -->
                <div class="card">
                    <div class="card-header">
                        <h5>Reward Prize Listing</h5>
                    </div>
                    <div class="card-block">
                        <div class="row">
                            <div class="col-sm-12 col-lg-1 col-md-1">
                                <label col-form-label">Country:</label>
                            </div>
                            <div class="col-sm-12 col-lg-2 col-md-2">
                                <select id="SCountry" class="form-control form-control-sm"></select>
                            </div>
                            <div class="col-sm-12 col-lg-1 col-md-1">
                                <label col-form-label">Category:</label>
                            </div>
                            <div class="col-sm-12 col-lg-3 col-md-3">
                                <select id="SCategory" class="form-control form-control-sm"></select>
                            </div>
                            <div class="col-sm-12 col-lg-1 col-md-1">
                                <label col-form-label">Status:</label>
                            </div>
                            <div class="col-sm-12 col-lg-2 col-md-2">
                                <select id="SStatus" class="form-control form-control-sm">
                                    <option value="">All</option>
                                    <option value="0">In-active</option>
                                    <option value="1">Active</option>
                                </select>
                            </div>
                            <div class="col-sm-12 col-lg-2 col-md-2">
                                <button type="button" id="btnSearch" onclick="BindRewardPrize();" class="btn btn-sm btn-grd-info"><i class="icon-magnifier"></i> Search</button>
                            </div>
                        </div>
                        <br />
                        <div class="row" style="padding-bottom:5px;">
                            <div class="col-sm-12 col-lg-3 col-md-3">
                                <button type="button" id="btnNew" onclick="AddNewPrize();" class="btn btn-sm  btn-grd-info"><i class="ion-plus-round"></i> Add Reward Prize</button>
                                <button type="button" id="btnUpload" class="btn btn-sm btn-grd-warning"><i class="icon-arrow-up-circle"></i> Upload</button>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table id="tblReward" class="table table-striped table-bordered widepadding" style="width:150%">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Status</th>
                                        <th>Item Code</th>
                                        <th>Category</th>
                                        <th>Name</th>
                                        <th>Product</th>
                                        <th>Reward<br />Points<br />Required</th>
                                        <th>Valid Till</th>
                                        <th>Unit Cost<br />(Local Currency)</th>
                                        <th>Suppiler</th>
                                        <th>Creation Date</th>
                                        <th>Quotation</th>
                                        <th>CreatedBy</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Page body end -->
</div>

<div id="RewardPrizeModal">
    <div class="md-content">
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="col-xl-3 col-lg-3 col-md-3 col-sm-1 col-xs-12">
                <p>Product</p>
                <img id="productphoto" src="@Url.Content("~/SystemImages/nophoto.jpg")" class="img-fluid m-b-10 img-product" alt="">
                <p><button onclick="RemoveProductPhoto();" class="btn col-sm-6 btn-sm btn-grd-danger">Remove</button></p>
            </div>
            <div class="col-xl-3 col-lg-3 col-md-3 col-sm-1 col-xs-12">
                <p>Quotation</p>
                <img id="quotationphoto" src="@Url.Content("~/SystemImages/nophoto.jpg")" class="img-fluid m-b-10 img-product" alt="">
                <p><button onclick="RemoveQuotationPhoto();" class="btn col-sm-6 btn-sm btn-grd-danger">Remove</button></p>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3">Status:</label>
            <div class="col-sm-8">
                <div class="form-radio">
                    <div class="radio radiofill radio-primary radio-inline">
                        <label>
                            <input id="rdoInactive" type="radio" name="rdoStatus" value="0" checked>
                            <i class="helper"></i>In-active
                        </label>
                    </div>
                    <div class="radio radiofill radio-primary radio-inline">
                        <label>
                            <input id="rdoActive" type="radio" name="rdoStatus" value="1">
                            <i class="helper"></i>Active
                        </label>
                    </div>
                </div>
                <span class="messages"></span>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Country:</label>
            <div class="col-sm-8">
                <select id="ddlCountry" onchange="GenerateItemCode()" class="form-control">
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Item Code:</label>
            <div class="col-sm-8">
                <input id="txtItemCode" readonly type="text" maxlength="10" class="form-control">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Category:</label>
            <div class="col-sm-8">
                <select id="ddlCategory" class="form-control">
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Product Name:</label>
            <div class="col-sm-8">
                <input id="txtProductName" type="text" maxlength="400" class="form-control">
            </div>
        </div>
        @*<div class="form-group row">
                <label class="col-sm-4 col-form-label">Product Photo:</label>
                <div class="col-sm-8">
                    <input type="file" class="form-control">
                </div>
            </div>*@
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Reward Points Required:</label>
            <div class="col-sm-8">
                <input id="txtPoints" type="text" maxlength="13" class="form-control point1 align-right">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Valid Till:</label>
            <div class="col-sm-8">
                <input id="txtValidTill" type="text" readonly class="form-control align-center">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3">Details:</label>
            <div class="col-sm-8">
                <div class="form-radio">
                    <div class="radio radiofill radio-primary radio-inline">
                        <label>
                            <input id="rdoURL" type="radio" name="rdoDetails" value="0" checked>
                            <i class="helper"></i>External URL
                        </label>
                    </div>
                    <div class="radio radiofill radio-primary radio-inline">
                        <label>
                            <input id="rdoDetailPage" type="radio" name="rdoDetails" value="1">
                            <i class="helper"></i>Detail Page
                        </label>
                    </div>
                </div>
                <span class="messages"></span>
            </div>
        </div>
        <div id="divURL" class="form-group row">
            <label class="col-sm-3 col-form-label">URL:</label>
            <div class="col-sm-8">
                <input id="txtURL" type="text" maxlength="1000" class="form-control">
            </div>
        </div>
        <div id="divDetailInfo" class="form-group row">
            <label class="col-sm-3 col-form-label">Product Descriptions:</label>
            <div class="col-sm-8">
                <textarea id="txtProductDescriptions" class="form-control" maxlength="4000"></textarea>
            </div>
        </div>
        <div class="form-group row" style="margin-bottom:0px">
            <label class="col-sm-3 col-form-label">D-Link Unit Cost:<br /><span style="font-size:11px">(Local Currency)</span></label>
            <div class="col-sm-8">
                <input id="txtUnitCost" type="text" maxlength="13" class="form-control point2 align-right">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Name of Supplier:</label>
            <div class="col-sm-8">
                <input id="txtSupplierName" type="text" maxlength="100" class="form-control">
            </div>
        </div>
        @*<div class="form-group row">
                <label class="col-sm-4 col-form-label">Quotation:</label>
                <div class="col-sm-8">
                    <input type="file" class="form-control">
                </div>
            </div>*@
        <div id="divSave" class="form-group row div-centerbtn">
            <div class="col-sm-3">
                <button type="button" id="btnClose" onclick="RewardPrizeClose();" class="btn  btn-grd-inverse">Close</button>
            </div>
            <div class="col-sm-3">
                <button type="button" id="btnSave" onclick="RewardPrizeSave();" class="btn  btn-grd-info"><span id="btnSaveText">Save</span></button>
            </div>
        </div>
    </div>
</div>

<div id="RewardImportModal">
    <div class="md-content">
        <div class="row" style="padding:10px">
            <div class="table-responsive">
                <table id="tblRewardPopUp" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th>Row</th>
                            <th>Status</th>
                            <th>Message</th>
                            <th>Contry</th>
                            <th>Category</th>
                            <th>Name</th>
                            <th>Reward Points<br /> Required</th>
                            <th>Valid Till</th>
                            <th>Page Type</th>
                            <th>External URL</th>
                            <th>Product Descriptions</th>
                            <th>Unit Cost</th>
                            <th>Suppiler</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
        <div id="divSave" class="form-group row div-centerbtn">
            <div class="col-sm-3">
                <button type="button" id="btnImportClose" onclick="ImportClose();" class="btn  btn-grd-inverse">Cancel</button>
            </div>
            <div id="divconfirm" class="col-sm-3">
                <button type="button" id="btnImportConfirm" onclick="ImportConfirm();" class="btn  btn-grd-info"><span id="btnSaveText">Confirm</span></button>
            </div>
        </div>
    </div>
</div>

<input id="productupload" accept="image/*" class="hidden" type="file" onchange="readURL(this,'productphoto');">
<input id="quotationupload" accept="image/*" class="hidden" type="file" onchange="readURL(this,'quotationphoto');">
<input id="rewardprizeupload" accept=".csv" class="hidden" type="file">

<input id="HRemoveProduct" type="hidden" />
<input id="HRemoveQuotation" type="hidden" />
<input id="HMode" type="hidden" />
<input id="Hproductphoto" type="hidden" />
<input id="Hquotation" type="hidden" />

<input id="HGetProductCategory" type="hidden" value="@Url.Action("GetProductCategory", "api/ProductCategoryApi")" />
<input id="HGetRewardPrize" type="hidden" value="@Url.Action("GetRewardPrize", "api/RewardApi")" />
<input id="imgnophoto" type="hidden" value="@Url.Content("~/SystemImages/nophoto.jpg")" />
<input id="HRewardPrizeCUD" type="hidden" value="@Url.Action("RewardPrize_CUD", "Reward")" />
<input id="HCheckRewardImport" type="hidden" value="@Url.Action("CheckRewardImport", "Reward")" />
<input id="HRewardImportConfrim" type="hidden" value="@Url.Action("RewardImportConfirm", "Reward")" />
<input id="HGetMimimumRedemptionPoints" type="hidden" value="@Url.Action("GetCountry", "api/CountryApi")" />
<input id="HGenerateItemCode" type="hidden" value="@Url.Action("GenerateItemCode", "api/RewardApi")" />

@section Scripts{
    <script src="@Url.Content("~/Scripts/reward.js?v=45")"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            RewardPrizeLoad();
        });
    </script>
}