Controllers/PartnerController.cs
using CKM_CommonFunction;
using ClosedXML.Excel;
using ErrorLog_BL;
using Message_BL;
using Newtonsoft.Json;
using Partner_BL;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using VPPModel;

namespace VPPWeb.Controllers
{
    public class PartnerController : Controller
    {
        public ActionResult PartnerList()
        {
            return View();
        }

        public ActionResult PartnerLoginFrequent()
        {
            return View();
        }

        [HttpPost]
        public string CheckRevisePartnerImport()
        {
            MessageBL messageBL = new MessageBL();
            PartnerModel partnerModel = new PartnerModel();
            if (Request.Files["VipPartnerReviseUpload"].FileName.EndsWith(".xlsx"))
            {
                Stream stream = Request.Files["VipPartnerReviseUpload"].InputStream;

                CommonFunction commonFunction = new CommonFunction();
                DataTable csvTable = commonFunction.ExceltoDatatable(stream);

                if (!csvTable.Columns.Contains("Register_No") || !csvTable.Columns.Contains("Company_Name") ||                  
                    !csvTable.Columns.Contains("FirstName") || !csvTable.Columns.Contains("LastName") ||
                    !csvTable.Columns.Contains("Phone") || !csvTable.Columns.Contains("Email") ||
                    !csvTable.Columns.Contains("Date_Of_Event") || !csvTable.Columns.Contains("DSS_EventCode") ||
                    !csvTable.Columns.Contains("EventName") || !csvTable.Columns.Contains("Country2") ||
                    !csvTable.Columns.Contains("RewardPoints"))
                {
                    MessageModel messageModel = new MessageModel
                    {
                        MessageID = "E015"
                    };
                    return messageBL.Message_Select(messageModel);
                }

                partnerModel.ReviseImportJson = commonFunction.DataTableToJSONWithJSONNet(csvTable);

                PartnerBL partnerBL = new PartnerBL();

                return partnerBL.CheckRevisePartnerImport(partnerModel);
            }
            else
            {
                MessageModel messageModel = new MessageModel
                {
                    MessageID = "E014"
                };
                return messageBL.Message_Select(messageModel);
            }
        }

        [HttpPost]
        public string CheckStandardPartnerImport()
        {
            MessageBL messageBL = new MessageBL();
            PartnerModel partnerModel = new PartnerModel();
            if (Request.Files["VipPartnerUpload"].FileName.EndsWith(".xlsx"))
            {
                Stream stream = Request.Files["VipPartnerUpload"].InputStream;

                CommonFunction commonFunction = new CommonFunction();
                DataTable csvTable = commonFunction.ExceltoDatatable(stream);

                if (!csvTable.Columns.Contains("Register_No") || !csvTable.Columns.Contains("Company_Name") ||
                    !csvTable.Columns.Contains("Address") || !csvTable.Columns.Contains("City") ||
                    !csvTable.Columns.Contains("ZipCode") || !csvTable.Columns.Contains("Country") ||
                    !csvTable.Columns.Contains("Website") || !csvTable.Columns.Contains("Location_No") ||
                    !csvTable.Columns.Contains("Partner_Type") || !csvTable.Columns.Contains("Business_Focus") ||
                    !csvTable.Columns.Contains("EmailNoti") || !csvTable.Columns.Contains("Prefix") ||
                    !csvTable.Columns.Contains("FirstName") || !csvTable.Columns.Contains("LastName") ||
                    !csvTable.Columns.Contains("Phone") || !csvTable.Columns.Contains("Email") ||
                    !csvTable.Columns.Contains("Job_Title"))
                {
                    MessageModel messageModel = new MessageModel
                    {
                        MessageID = "E015"
                    };
                    return messageBL.Message_Select(messageModel);
                }

                partnerModel.StandardImportJson = commonFunction.DataTableToJSONWithJSONNet(csvTable);

                PartnerBL partnerBL = new PartnerBL();

                return partnerBL.CheckStandardPartnerImport(partnerModel);
            }
            else
            {
                MessageModel messageModel = new MessageModel
                {
                    MessageID = "E014"
                };
                return messageBL.Message_Select(messageModel);
            }
        }

        [HttpPost]
        public string PartnerStandardImportConfirm()
        {
            MessageBL messageBL = new MessageBL();
            string j1 = HttpContext.Request.Params.Get("PartnerModel");
            PartnerModel partnerModel = JsonConvert.DeserializeObject<PartnerModel>(j1);

            try
            {
                if (Request.Files["VipPartnerUpload"].FileName.EndsWith(".xlsx"))
                {
                    Stream stream = Request.Files["VipPartnerUpload"].InputStream;
                    CommonFunction commonFunction = new CommonFunction();
                    DataTable csvTable = commonFunction.ExceltoDatatable(stream);

                    partnerModel.FileName = Request.Files["VipPartnerUpload"].FileName;
                    partnerModel.StandardImportJson = commonFunction.DataTableToJSONWithJSONNet(csvTable);

                    PartnerBL partnerBL = new PartnerBL();
                    
                    partnerBL.Partner_StandardImportConfirm(partnerModel);

                    MessageModel messageModel = new MessageModel
                    {
                        MessageID = "I006"
                    };
                    return messageBL.Message_Select(messageModel);
                }
                else
                {
                    MessageModel messageModel = new MessageModel
                    {
                        MessageID = "E014"
                    };
                    return messageBL.Message_Select(messageModel);
                }
            }
            catch (Exception exception)
            {
                ErrorLogModel errorLogModel = new ErrorLogModel
                {
                    ErrorMessage = exception.Message,
                    UpdatedBy = partnerModel.UpdatedBy
                };

                ErrorLogBL errorLogBL = new ErrorLogBL();
                errorLogBL.ErrorLog_Insert(errorLogModel);

                MessageModel messageModel = new MessageModel
                {
                    MessageID = "E014"
                };
                return messageBL.Message_Select(messageModel);
            }

        }

        [HttpPost]
        public string PartnerReviseImportConfirm()
        {
            MessageBL messageBL = new MessageBL();
            string j1 = HttpContext.Request.Params.Get("PartnerModel");
            PartnerModel partnerModel = JsonConvert.DeserializeObject<PartnerModel>(j1);

            try
            {
                if (Request.Files["VipPartnerReviseUpload"].FileName.EndsWith(".xlsx"))
                {
                    Stream stream = Request.Files["VipPartnerReviseUpload"].InputStream;
                    CommonFunction commonFunction = new CommonFunction();
                    DataTable csvTable = commonFunction.ExceltoDatatable(stream);

                    partnerModel.FileName = Request.Files["VipPartnerReviseUpload"].FileName;
                    partnerModel.ReviseImportJson = commonFunction.DataTableToJSONWithJSONNet(csvTable);

                    PartnerBL partnerBL = new PartnerBL();

                    partnerBL.Partner_ReviseImportConfirm(partnerModel);

                    MessageModel messageModel = new MessageModel
                    {
                        MessageID = "I006"
                    };
                    return messageBL.Message_Select(messageModel);
                }
                else
                {
                    MessageModel messageModel = new MessageModel
                    {
                        MessageID = "E014"
                    };
                    return messageBL.Message_Select(messageModel);
                }
            }
            catch (Exception exception)
            {
                ErrorLogModel errorLogModel = new ErrorLogModel
                {
                    ErrorMessage = exception.Message,
                    UpdatedBy = partnerModel.UpdatedBy
                };

                ErrorLogBL errorLogBL = new ErrorLogBL();
                errorLogBL.ErrorLog_Insert(errorLogModel);

                MessageModel messageModel = new MessageModel
                {
                    MessageID = "E014"
                };
                return messageBL.Message_Select(messageModel);
            }

        }

        private string CreateRandomPassword(int length = 15)
        {
            // Create a string of characters, numbers, special characters that allowed in the password  
            string validChars = "ABCDEFGHJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*?_-";
            Random random = new Random();

            // Select one random character at a time from the string  
            // and create an array of chars  
            char[] chars = new char[length];
            for (int i = 0; i < length; i++)
            {
                chars[i] = validChars[random.Next(0, validChars.Length)];
            }
            return new string(chars);
        }

        //public string SendWelcomeMail()
        //{
        //    MessageBL messageBL = new MessageBL();
        //    string j1 = HttpContext.Request.Params.Get("PartnerModel");
        //    PartnerModel partnerModel = JsonConvert.DeserializeObject<PartnerModel>(j1);
        //    try
        //    {

Views/Partner/PartnerList.cshtml
@{
    ViewBag.Title = "PartnerList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="page-wrapper">
    <!-- Page body start -->
    <div class="page-body">
        <div class="row">
            <div class="col-sm-12">
                <!-- Basic Form Inputs card start -->
                <div class="card">
                    <div class="card-header">
                        <h5>VIP Partner Listing</h5>
                    </div>
                    <div class="card-block">
                        <div class="card searchcard" id="AdvanceSearch">
                            <div class="card-body">

                                <div class="form-group row">
                                    <div class="col-sm-2">
                                        <label class="col-form-label form-label-sm">Country:</label>
                                        <select id="SCountry" class="form-control form-control-sm"></select>
                                    </div>
                                    <div class="col-sm-2">
                                        <label class="col-form-label">Company Name:</label>
                                        <input id="StxtCompanyName" type="text" class="form-control form-control-sm" />
                                    </div>
                                    <div class="col-sm-2">
                                        <label class="col-form-label">Name:</label>
                                        <input id="StxtName" type="text" class="form-control form-control-sm" />
                                    </div>
                                    <div class="col-sm-2">
                                        <label class="col-form-label">Email:</label>
                                        <input id="StxtEmail" type="search" maxlength="10" class="form-control form-control-sm date">
                                    </div>
                                    <div class="col-sm-2">
                                        <label class=" col-form-label">Status:</label>
                                        <select id="SPartnerStatus" class="form-control form-control-sm">
                                            <option value="">All</option>
                                            <option value="1">New</option>
                                            <option value="2">Wel</option>
                                            <option value="3">Re1</option>
                                            <option value="4">Re2</option>
                                            <option value="5">RPM</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer searchfooter div-centerbtn">
                                <btn id="btnSearchClear" class="btn btn-sm searchclearbtn"><i class="icofont icofont-delete"></i> Clear</btn>
                                <btn id="btnSearchEvent" class="btn btn-sm searchbtn"><i class="ion-ios-search-strong"></i> Search</btn>
                            </div>
                        </div>
                        <!--<div class="row" style="padding-bottom:5px;">
        <div class="col-sm-12 col-lg-2 col-md-3">
            <button type="button" id="btnStandardUpload" class="btn btn-block btn-grd-inverse"><i class="icon-arrow-up-circle"></i> Standard</button>
        </div>
        <div class="col-sm-12 col-lg-2 col-md-3">
            <button type="button" id="btnReviseUpload" class="btn btn-block btn-grd-warning"><i class="icon-arrow-up-circle"></i> Revise</button>
        </div>-->
                        @*<div class="col-sm-12 col-lg-3 col-md-4">
            <button type="button" id="btnWelcomeEmail" class="btn btn-block btn-grd-primary"><i class="ti-email"></i> Send Welcome Email</button>
        </div>*@
                        <!--</div>-->
                        @*<div class="row" style="padding-bottom:5px;font-size:11px;float:right">
                            <span class="pcoded-badge label label-primary">New</span>New Partner&nbsp;
                            <span class="pcoded-badge label label-success">Wel</span>Sent Welcome Email&nbsp;
                            <span class="pcoded-badge label label-inverse">Re1</span>Resent Email 1st Time&nbsp;
                            <span class="pcoded-badge label label-warning">Re1</span>Resent Email 2nd Time&nbsp;
                            <span class="pcoded-badge label label-danger">RPM</span>Inform RP Manager
                        </div>*@
                        <div class="table-responsive">
                            <table id="tblVIPPartner" class="table table-striped table-bordered" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>Action</th>
                                        @*<th>Status</th>*@
                                        <th>Country</th>
                                        <th>Company</th>
                                        @*<th>Address</th>*@
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Points</th>
                                        @*<th>City</th>*@
                                        <th>Partner Type</th>
                                        <th>Business Focus</th>
                                        <th>Phone</th>
                                        <th>Job Title</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Page body end -->
</div>

<div id="PartnerImportModal">
    <div class="md-content">
        <div class="row" style="padding:10px">
            <div class="table-responsive">
                <table id="tblPartnerPopUp" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th>Row</th>
                            <th>Status</th>
                            <th>Message</th>
                            <th>Register No</th>
                            <th>Company Name</th>
                            <th>Address</th>
                            <th>City</th>
                            <th>Zip Code</th>
                            <th>Country</th>
                            <th>Website</th>
                            <th>Location No</th>
                            <th>Partner Type</th>
                            <th>Business Focus</th>
                            <th>Email Noti</th>
                            <th>Prefix</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Phone</th>
                            <th>Email</th>
                            <th>Job Title</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
        <div id="divSave" class="form-group row div-centerbtn">
            <div class="col-sm-3">
                <button type="button" id="btnPartnerImportClose" onclick="PartnerImportClose();" class="btn btn-block btn-grd-inverse">Cancel</button>
            </div>
            <div id="divconfirm" class="col-sm-3">
                <button type="button" id="btnPartnerImportConfirm" onclick="PartnerImportConfirm();" class="btn btn-block btn-grd-info"><span id="btnSaveText">Confirm</span></button>
            </div>
        </div>
    </div>
</div>

<div id="PartnerReviseImportModal">
    <div class="md-content">
        <div class="row" style="padding:10px">
            <div class="table-responsive">
                <table id="tblPartnerRevisePopUp" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th>Row</th>
                            <th>Status</th>
                            <th>Message</th>
                            <th>Register No</th>
                            <th>Company Name</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Phone</th>
                            <th>Email</th>
                            <th>Date Of Event</th>
                            <th>DSS Event Code</th>
                            <th>Event Name</th>
                            <th>Country2</th>
                            <th>Reward Points</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
        <div id="divSave" class="form-group row div-centerbtn">
            <div class="col-sm-3">
                <button type="button" id="btnPartnerReviseImportClose" class="btn btn-block btn-grd-inverse">Cancel</button>
            </div>
            <div id="divconfirmrevise" class="col-sm-3">
                <button type="button" id="btnPartnerReviseImportConfirm" class="btn btn-block btn-grd-info"><span id="btnSaveText">Confirm</span></button>
            </div>
        </div>
    </div>
</div>


<input id="VipPartnerUpload" accept=".xlsx" class="hidden" type="file">
<input id="VipPartnerReviseUpload" accept=".xlsx" class="hidden" type="file">
<input id="HSendWelcomeMail" type="hidden" value="@Url.Action("SendWelcomeMail", "Partner")" />
<input id="HGetVIPPartner" type="hidden" value="@Url.Action("GetVIPPartner", "api/PartnerApi")" />
<input id="HCheckStandardImport" type="hidden" value="@Url.Action("CheckStandardPartnerImport", "Partner")" />
<input id="HCheckReviseImport" type="hidden" value="@Url.Action("CheckRevisePartnerImport", "Partner")" />
<input id="HPartnerStandardImportConfirm" type="hidden" value="@Url.Action("PartnerStandardImportConfirm", "Partner")" />
<input id="HPartnerReviseImportConfirm" type="hidden" value="@Url.Action("PartnerReviseImportConfirm", "Partner")" />
<input id="HGetCountry" type="hidden" value="@Url.Action("GetCountry", "api/CountryApi")" />

@section Scripts{
    <script src="@Url.Content("~/Scripts/partner.js?v=5")"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            LoadVIPPartner();
        });
    </script>
}

Views/Partner/PartnerLoginFrequent.cshtml
@{
    ViewBag.Title = "PartnerLoginFrequent";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-wrapper">
    <!-- Page body start -->
    <div class="page-body">
        <div class="row">
            <div class="col-sm-12">
                <!-- Basic Form Inputs card start -->
                <div class="card">
                    <div class="card-header">
                        <h5>Partner Log in Frequency</h5>
                    </div>
                    <div class="card-block">
                        <div class="table-responsive">
                            <table id="tblPartnerLoginLog" class="table table-striped table-bordered" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>Action</th>
                                        <th>Country</th>
                                        <th>Company</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Frequent</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Page body end -->
</div>

<div id="PartnerLoginHistoryModal">
    <div class="md-content">
        <div class="table-responsive">
            <table id="tblPartnerLoginLogDetail" class="table table-striped" style="width:100%">
                <thead>
                    <tr>
                        <th>Email</th>
                        <th>Log in Date</th>
                    </tr>
                </thead>
            </table>
        </div>
        <div class="form-group row div-centerbtn">
            <div class="col-sm-3">
                <button type="button" id="btnOK" onclick="PartnerLoginHistoryClose();" class="btn btn-block btn-grd-inverse">Close</button>
            </div>
        </div>
    </div>
</div>

<input id="HGetPartnerLoginLog" type="hidden" value="@Url.Action("GetPartnerLoginLog", "api/PartnerApi")" />
<input id="HGetPartnerLoginLogDetail" type="hidden" value="@Url.Action("GetPartnerLoginLogDetail", "api/PartnerApi")" />

@section Scripts{
    <script src="@Url.Content("~/Scripts/partner.js?v=1")"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            PartnerloginLogLoad();
        });
    </script>
}