Controllers/CaseStudiesController.cs
using DigitalLibrary_BL;
using ErrorLog_BL;
using Message_BL;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VPPModel;
using CaseStudies_BL;

namespace VPPWeb.Controllers
{
    public class CaseStudiesController : Controller
    {
        // GET: CaseStudies
        public ActionResult CaseStudiesListing()
        {
            return View();
        }

        [HttpPost]
        public string CaseStudies_CUD()
        {
            string j1 = HttpContext.Request.Params.Get("CaseStudiesModel");
            CaseStudiesModel caseStudiesModel = JsonConvert.DeserializeObject<CaseStudiesModel>(j1);
            try
            {
                CaseStudiesBL caseStudiesBL = new CaseStudiesBL();

                if (caseStudiesModel.Mode.Equals("New"))
                {
                    caseStudiesModel.CaseStudiesCode = caseStudiesBL.GenerateCaseStudiesCode(caseStudiesModel);
                }

                if (System.IO.File.Exists(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + caseStudiesModel.ThumbnailRemove)))
                    System.IO.File.Delete(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + caseStudiesModel.ThumbnailRemove));

                if (System.IO.File.Exists(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + caseStudiesModel.ResourceRemove)))
                    System.IO.File.Delete(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + caseStudiesModel.ResourceRemove));

                for (int i = 0; i < Request.Files.Count; i++)
                {
                    string key = Request.Files.GetKey(i);
                    if (key == "resource")
                    {
                        if (System.IO.File.Exists(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + caseStudiesModel.ThumbnailImage)))
                            System.IO.File.Delete(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + caseStudiesModel.ThumbnailImage));

                        caseStudiesModel.ResourceFile = "CaseStudies/Resource/" + caseStudiesModel.CaseStudiesCode + '_' + DateTime.Now.ToString("yyyymmddhhmmss") + Path.GetExtension(Request.Files[i].FileName);
                        caseStudiesModel.ResourceFileName = Request.Files[i].FileName;

                        Request.Files[i].SaveAs(Path.Combine(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/"), caseStudiesModel.ResourceFile));
                    }

                    if (key == "thumbnail")
                    {
                        if (System.IO.File.Exists(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + caseStudiesModel.ThumbnailImage)))
                            System.IO.File.Delete(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/" + caseStudiesModel.ThumbnailImage));

                        caseStudiesModel.ThumbnailImage = "CaseStudies/Thumbnail/" + caseStudiesModel.CaseStudiesCode + '_' + DateTime.Now.ToString("yyyymmddhhmmss") + Path.GetExtension(Request.Files[i].FileName);
                        caseStudiesModel.ThumbnailImageName = Request.Files[i].FileName;

                        Request.Files[i].SaveAs(Path.Combine(System.Web.Hosting.HostingEnvironment.MapPath("~/SystemImages/"), caseStudiesModel.ThumbnailImage));
                    }
                }

                return caseStudiesBL.Casestudies_CUD(caseStudiesModel);
            }
            catch (Exception exception)
            {
                ErrorLogModel errorLogModel = new ErrorLogModel
                {
                    ErrorMessage = exception.Message,
                    UpdatedBy = caseStudiesModel.UpdatedBy
                };

                ErrorLogBL errorLogBL = new ErrorLogBL();
                errorLogBL.ErrorLog_Insert(errorLogModel);

                MessageBL messageBL = new MessageBL();
                MessageModel messageModel = new MessageModel
                {
                    MessageID = "E007"
                };
                return messageBL.Message_Select(messageModel);
            }
        }
    }
}

Views/CaseStudies/CaseStudiesListing.cshtml
@{
    ViewBag.Title = "CaseStudiesListing";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-wrapper">
    <!-- Page body start -->
    <div class="page-body">
        <div class="row">
            <div class="col-sm-12">
                <!-- Basic Form Inpus card start -->
                <div class="card">
                    <div class="card-header">
                        <h5>CaseStudies List</h5>
                    </div>
                    <div class="card-block">
                        <div class="card searchcard" id="AdvanceSearch">
                            <div class="card-body">
                                <div class="form-group row">
                                    <div class="col-sm-4">
                                        <label class=" col-form-label">Title:</label>
                                        <input id="STitle" type="search" maxlength="200" class="form-control form-control-sm">
                                    </div>
                                    <div class="col-sm-2">
                                        <label class=" col-form-label">Status:</label>
                                        <select id="SStatus" class="form-control form-control-sm">
                                            <option value="">All</option>
                                            <option value="1">Active</option>
                                            <option value="0">In-active</option>
                                        </select>
                                    </div>
                                    <div class="col-sm-2">
                                        <label class=" col-form-label">Category:</label>
                                        <select id="SIndustryCategory" class="form-control form-control-sm">
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer searchfooter div-centerbtn">
                                <btn id="btnSearchCaseStudiesClear" class="btn btn-sm searchclearbtn"><i class="icofont icofont-delete"></i> Clear</btn>
                                <btn id="btnSearchCaseStudies" class="btn btn-sm searchbtn"><i class="ion-ios-search-strong"></i> Search</btn>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table id="tblCaseStudies" class="table table-striped table-bordered" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>Action</th>
                                        <th>Status</th>
                                        <th>Title</th>
                                        <th>Description</th>
                                        <th>Category</th>
                                        <th>Upload Date</th>
                                        <th>Download</th>
                                        <th>Links</th>
                                        <th>Thumbnail</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Page body end -->
</div>

<div id="CaseStudiesModal">
    <div class="md-content">
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Status:</label>
            <div class="col-sm-8">
                <div class="form-radio">
                    <div class="radio radiofill radio-primary radio-inline">
                        <label>
                            <input id="rdoInactive" type="radio" name="rdoStatus" value="0" checked>
                            <i class="helper"></i>In-active
                        </label>
                    </div>
                    <div class="radio radiofill radio-primary radio-inline">
                        <label>
                            <input id="rdoActive" type="radio" name="rdoStatus" value="1">
                            <i class="helper"></i>Active
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">CaseStudies Code:</label>
            <div class="col-sm-4">
                <input id="txtCaseStudiesCode" readonly type="text" maxlength="10" class="form-control form-control-sm">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Upload By:</label>
            <div class="col-sm-4">
                <input id="txtUploadBy" readonly type="text" maxlength="10" class="form-control form-control-sm">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Upload Date:</label>
            <div class="col-sm-2">
                <select class="form-control form-control-sm" id="uploadmonth">
                    <option value="01">Jan</option>
                    <option value="02">Feb</option>
                    <option value="03">Mar</option>
                    <option value="04">Apr</option>
                    <option value="05">May</option>
                    <option value="06">Jun</option>
                    <option value="07">Jul</option>
                    <option value="08">Aug</option>
                    <option value="09">Sep</option>
                    <option value="10">Oct</option>
                    <option value="11">Nov</option>
                    <option value="12">Dec</option>
                </select>
            </div>
            <div class="col-sm-2">
                <select class="form-control form-control-sm" id="uploadyear">
                    <option value="2012">2012</option>
                    <option value="2013">2013</option>
                    <option value="2014">2014</option>
                    <option value="2015">2015</option>
                    <option value="2016">2016</option>
                    <option value="2017">2017</option>
                    <option value="2018">2018</option>
                    <option value="2019">2019</option>
                    <option value="2020">2020</option>
                    <option value="2021">2021</option>
                    <option value="2022">2022</option>
                    <option value="2023">2023</option>
                    <option value="2024">2024</option>
                    <option value="2025">2025</option>
                    <option value="2026">2026</option>
                    <option value="2027">2027</option>
                    <option value="2028">2028</option>
                    <option value="2029">2029</option>
                    <option value="2030">2030</option>
                    <option value="2031">2031</option>
                    <option value="2032">2032</option>
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Product Category:</label>
            <div id="divProductCategoryList" class="col-sm-9">
                <div class="col-sm-12 checkbox-fade fade-in-primary" style="padding:0">
                    <label>
                        <input type="checkbox" id="chkAll" name="Language" value="HTML" class="input-danger">
                        <span class="cr">
                            <i class="cr-icon icofont icofont-ui-check txt-primary"></i>
                        </span>
                        <span>All</span>
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Industry Category:</label>
            <div class="col-sm-9">
                <select class="form-control form-control-sm" id="IndustryCategory">
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Importance:</label>
            <div class="col-sm-9">
                <select class="form-control form-control-sm" id="Importance">
                    <option value="05">Highest</option>
                    <option value="04">High</option>
                    <option value="03">Medium</option>
                    <option value="02">Low</option>
                    <option value="01">Least</option>
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Resource (PDF/Image):</label>
            <div id="divResource" class="col-sm-9">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Thumbnail Image:</label>
            <div id="divThumbnail" class="col-sm-9">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Title:</label>
            <div class="col-sm-9">
                <input id="txtTitle" type="text" maxlength="200" class="form-control form-control-sm ">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Description:</label>
            <div class="col-sm-9">
                <textarea id="txtDescription" maxlength="1000" class="form-control form-control-sm"></textarea>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Download:</label>
            <div class="col-sm-9">
                <input id="txtDownloadCount" readonly type="text" class="form-control form-control-sm align-right">
            </div>
        </div>
        <div id="divSave" class="form-group row div-centerbtn">
            <div class="col-sm-3">
                <button type="button" id="btnCaseStudiesClose" class="btn btn-block btn-grd-inverse">Close</button>
            </div>
            <div class="col-sm-3">
                <button type="button" id="btnCaseStudiesSave" class="btn btn-block btn-grd-info"><span id="btnSaveText">Save</span></button>
            </div>
        </div>
    </div>
</div>

<input id="HGetMarketingProductCategory" type="hidden" value="@Url.Action("GetMarketingProductCategory", "api/MarketingAssetsApi")" />

<input id="HGetIndustryCategory" type="hidden" value="@Url.Action("GetIndustryCategory", "api/IndustryCategoryApi")" />
<input id="HGetCaseStudies" type="hidden" value="@Url.Action("GetCaseStudies", "api/CaseStudiesApi")" />
<input type="hidden" id="HMode" />
<input id="HCaseStudiesCUD" type="hidden" value="@Url.Action("CaseStudies_CUD", "CaseStudies")" />

@section Scripts{
    <script src="@Url.Content("~/Scripts/casestudies.js?v=2")"></script>
    <script src="@Url.Content("~/Scripts/fileupload.js?v=3")"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            CaseStudiesLoad();
        });
    </script>
}